#login_homepage:
#    path:  /hello/{name}
#    defaults: { _controller: LoginBundle:Default:index }
#    
#iniciar_sesion:
#    path:  /iniciarSesion
#    defaults: { _controller: LoginBundle:Default:iniciarSesion }    
#
#LoginBundle_backend_administrador:
#    resource: "@LoginBundle/Resources/config/routing/administrators.yml"
#    prefix:   /backend/administrador    

usuario_login:
    path:  /login
    defaults: { _controller: LoginBundle:Default:login }

usuario_login_check:
    path:  /login_check    

usuario_logout: 
    path:  /logout    

#iniciar_sesion:
#    path:  /iniciarSesion
#    defaults: { _controller: LoginBundle:Default:iniciar }
    
cerrar_sesion:
    path:  /cerrarSesion
    defaults: { _controller: LoginBundle:Default:cerrar }
    
usuario_perfil:
    path:  /perfil
    defaults: { _controller: LoginBundle:Default:perfil }  

usuario_perfilEditar:
    path:  /perfilEditar
    defaults: { _controller: LoginBundle:Default:perfilEditar }  

usuario_hello:
    path:  /hello
    defaults: { _controller: LoginBundle:Default:test }  
    
usuario_registro:
    path: /registro
    defaults: { _controller: LoginBundle:Default:registro }
    