#portada_homepage:
#    path:  /hello/{name}
#    defaults: { _controller: PortadaBundle:Default:index }
    
#portada_producto_buscar:
#    path: /portada_producto_buscar
#    defaults: { _controller: PortadaBundle:Portada:buscar }

#portada_producto_listar:
#    path: /portada_producto_listar
#    defaults: { _controller: PortadaBundle:Portada:listar }

portada_producto_ver:
    path: /portada_producto_ver/{id}
    defaults: { _controller: PortadaBundle:Portada:ver }

portada_producto_inicio:
    path: /portada_producto_inicio
    defaults: { _controller: PortadaBundle:Portada:inicio }

portada_tarifas:
    path: /portada_tarifas
    defaults: { _controller: PortadaBundle:Portada:tarifas }

portada_historia:
    path: /portada_historia
    defaults: { _controller: PortadaBundle:Portada:historia }

modificar_anuncio:
    path: /modificar_anuncio
    defaults: { _controller: PortadaBundle:Portada:modificarAnuncio }

#Muestra la pagina para renovar el anuncio
renovar_anuncio:
    path: /renovar_anuncio
    defaults: { _controller: PortadaBundle:Portada:renovarAnuncio }

#Actualiza el anuncio por 30 dias mas apartir de hoy, se utiliza con javascript+ajax
renovar:
    path: /renovar
    defaults: { _controller: PortadaBundle:Portada:renovar }

notificar_venta:
    path: /notificar_venta
    defaults: { _controller: PortadaBundle:Portada:notificarVenta }
    
notificar:
    path: /notificar
    defaults: { _controller: PortadaBundle:Portada:notificar }    
