portada_homepage:
    path:  /hello/{name}
    defaults: { _controller: PortadaBundle:Default:index }
    
#portada_producto_buscar:
#    path: /portada_producto_buscar
#    defaults: { _controller: PortadaBundle:Portada:buscar }

#portada_producto_listar:
#    path: /portada_producto_listar
#    defaults: { _controller: PortadaBundle:Portada:listar }

portada_producto_ver:
    path: /portada_producto_ver/{id}
    defaults: { _controller: PortadaBundle:Portada:ver }

portada_producto_inicio:
    path: /portada_producto_inicio
    defaults: { _controller: PortadaBundle:Portada:inicio }

portada_tarifas:
    path: /portada_tarifas
    defaults: { _controller: PortadaBundle:Portada:tarifas }

modificar_anuncio:
    path: /modificar_anuncio
    defaults: { _controller: PortadaBundle:Portada:modificarAnuncio }

renovar_anuncio:
    path: /renovar_anuncio
    defaults: { _controller: PortadaBundle:Portada:renovarAnuncio }

notificar_venta:
    path: /notificar_venta
    defaults: { _controller: PortadaBundle:Portada:notificarVenta }
