parameters:
#    entidades.example.class: miMoto\EntidadesBundle\Example

services:
#    entidades.example:
#        class: %entidades.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
