console:
    path:  /console/
    defaults: { _controller: ConsoleBundle:Console:console }
    methods: [GET]
#    requirements:
#        _method: GET


console_exec:
    path:  /console.{_format}
    defaults: { _controller: ConsoleBundle:Console:exec, _format: json }
    methods: [POST]
    requirements:
#        _method: POST
        _format: json
