services:
    coresphere_console.toolbar:
        class: CoreSphere\ConsoleBundle\DataCollector\DataCollector
        tags:
            - { name: data_collector, template: "ConsoleBundle:Toolbar:toolbar", id: "coresphere_console" }
