frontend_homepage:
    path:  /hello/{name}
    defaults: { _controller: FrontendBundle:Default:index }
    
producto_ver:
    path:  /ver/{id}
    defaults: { _controller: FrontendBundle:Default:ver }  
    
producto_nuevo:
    path: /nuevo
    defaults: { _controller: FrontendBundle:Default:nuevo }    
    
producto_editar:
    path: /editar/{id}
    defaults: { _controller: FrontendBundle:Default:editar }    
    
producto_carrusel:
    path: /carrusel/{id}
    defaults: { _controller: FrontendBundle:Default:carrusel }    

usuario_producto_nuevo:
    path: /usuario_producto_nuevo
    defaults: { _controller: FrontendBundle:UsuarioProducto:nuevo }   

usuario_producto_editar:
    path:  /usuario_producto_editar
    defaults: { _controller: FrontendBundle:UsuarioProducto:editar }  

usuario_producto_ver:
    path:  /usuario_producto_ver
    defaults: { _controller: FrontendBundle:UsuarioProducto:ver }  
    
ciudades:
    path: /ciudades
    defaults: { _controller: FrontendBundle:UsuarioProducto:ciudades }
    
razas:
    path: /razas
    defaults: { _controller: FrontendBundle:UsuarioProducto:razas }
    
